# Generated by Django 2.2.12 on 2020-05-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('working_hours', models.DecimalField(decimal_places=1, max_digits=10)),
                ('hourly_rate', models.IntegerField()),
                ('is_admin', models.CharField(max_length=1)),
                ('created_by', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
        ),
    ]
