# Generated by Django 2.2.12 on 2020-05-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollprocess', '0002_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='working_hours',
            field=models.IntegerField(),
        ),
    ]
