# Generated by Django 2.2.12 on 2020-05-16 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollprocess', '0004_auto_20200515_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 8, 24, 20, 824505)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 8, 24, 20, 824505)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_month',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 16, 8, 24, 20, 856505)),
        ),
    ]
