# Generated by Django 2.2.12 on 2020-05-16 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollprocess', '0006_auto_20200516_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 9, 51, 13, 85639)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.AutoField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 9, 51, 13, 85639)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_id',
            field=models.AutoField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_month',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 9, 51, 13, 116682)),
        ),
    ]
