# Generated by Django 2.2.12 on 2020-05-16 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollprocess', '0010_auto_20200516_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 10, 23, 15, 130068)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_admin',
            field=models.CharField(blank=True, default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 10, 23, 15, 130068)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_month',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 10, 23, 15, 167068)),
        ),
    ]
