# Generated by Django 2.2.12 on 2020-05-16 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollprocess', '0011_auto_20200516_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 11, 28, 9, 96046)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_admin',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 11, 28, 9, 96046)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_month',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 11, 28, 9, 127042)),
        ),
    ]
