# Generated by Django 2.2.12 on 2020-05-21 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollprocess', '0014_auto_20200521_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 21, 5, 19, 30, 970594)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 21, 5, 19, 30, 970594)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_month',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 21, 5, 19, 30, 998589)),
        ),
    ]
