# Generated by Django 2.2.12 on 2020-05-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollprocess', '0018_auto_20200523_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_month',
            field=models.DateField(),
        ),
    ]
