# Generated by Django 2.2.12 on 2020-05-23 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollprocess', '0022_auto_20200523_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 23, 10, 39, 0, 10186)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 23, 10, 39, 0, 10186)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_month',
            field=models.DateField(),
        ),
    ]
